# Generated by Django 4.0.5 on 2022-07-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name_en',
            field=models.CharField(max_length=200),
        ),
    ]
